### PR TITLE
Add external event handler for WebSocket connection events

### PR DESCRIPTION
**Pull request by ayonghosh**
Creating a new pull request after rebasing for #662

### CODE REVIEW

**Comment by DirectXMan12** [comment]
From #662: I'm still a bit torn as to whether or not errors like that should be actual exceptions. @samhed @kanaka thoughts? @ayonghosh would that also work for your use case?

Anyway, if not, this PR looks pretty reasonable to me.

**Comment by ayonghosh** [comment]
@DirectXMan12 that would work.

**Comment by samhed** [comment]
+1 for exceptions on websocket errors

**Comment by JeffLeFevre** [comment]
+1 on exceptions for websocket errors

**Comment by samhed** [comment]
To clarify, I do not think we should have a callback for WebSocket connection events. In my mind, the websocket handling should not leak to the user interface.

However, in #651 I have added a onDisconnected callback which allows you to specify a reason. We could perhaps use _fail(msg) here. Is there any situation where we wouldn't want to disconnect on WebSocket errors?

**Pull request closed without merging**
