### PR TITLE
Introduce new zlib implementation

### PR DESCRIPTION
**Pull request by DirectXMan12**
***WIP: Do Not Merge***

This is an initial shot at replacing our current zlib implementation (jsunzip) with a faster one.

I ran two different tests: one was running the `sl` program using a TigerVNC server, and the other was running `ls` against a qemu-hosted VM using qemu's built-in VNC support.  Numbers reported are based on the `vnc_playback.html` perf test.

For the `sl` test, the new implementation shows a slight improvement (maybe 10%).  The test was preformed based on a recording of the `sl` program.

For the `ls` test, the new implementation cut the time nearly in half in Chrome, and even more in Firefox.  The test was performed by running `ls -lR` on my home directory in the qemu-hosted VM.

Thoughts?

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Currently the only issue is that the output buffer is of fixed size -- it's currently set at 100k (it's only allocated once per instance though, so increasing the size doesn't have too much of a cost).  So far, this hasn't been an issue, but it could be, hypothetically.  We could also scale it dynamically based on screen size (which should have little impact on performance) or use a loop and join buffers together (which could have a significant impact on performance).

**Comment by DirectXMan12** [comment]
CC @kanaka , @samhed , @astrand

**Comment by DirectXMan12** [comment]
See also #431

**Comment by kanaka** [comment]
@DirectXMan12 Was getting the playback working again difficult? From the code changes it doesn't look like it was too bad (hopefully). I think we should get those changes in even if we don't add the pako change right away. BTW, in addition to the total time reported by playback, if you enable logging=info, you'll get some more timing information (per encoding type) in the javascript console. Might give a little more insight.

Anyways, since this change gives 10% boost overall even in the worst case this seems like a good candidate for merging. I think my only concern would be to make sure that we don't have a massive regression (broken or much slower) in some of the older browser versions that we still want to support.

**Comment by kanaka** [comment]
@DirectXMan12 BTW, it might be interesting to compare with an asm.js enabled zlib implementation: https://github.com/ukyo/zlib-asm That does mean getting an emscripten toolchain working, but since we probably want to switch a lot of the noVNC fast path to asm.js at some point, this might be a good place to start experimenting. I might even have some time to work on it this summer if you don't, although no promises.

**Comment by kanaka** [comment]
@DirectXMan12 and I forgot to say good work! It's exciting to see this starting to happen. There is a lot of potential areas for noVNC performance improvements: binary types, asm.js, web workers (especially now that firefox supports WebSockets in workers), SIMD.js, etc. And since some of those areas represent in-progress standards efforts, we also have an opportunity to contribute to state-of-the-art. noVNC is a fairly widely used project where those technologies can actually be used and tested using real-world conditions. So I think we are somewhat uniquely positioned to be able to contribute to the development of those technologies. The same was true with canvas and websockets back when noVNC started and I was able to make a few minor contributions to the Websocket protocol and Canvas API. If only we all had several more hours in the day :-) Maybe I can convince my faculty supervisor to let me work on this as part of my PhD.

**Comment by DirectXMan12** [comment]
> @DirectXMan12 Was getting the playback working again difficult? From the code changes it doesn't look like it was too bad (hopefully). I think we should get those changes in even if we don't add the pako change right away.

I concur.  It was really just a case of adapting it to work since the refactor (duplicating "test mode" outside of the RFB object's API) and changing it to create a new `RFB` object each iteration.

> BTW, in addition to the total time reported by playback, if you enable logging=info, you'll get some more timing information (per encoding type) in the javascript console. Might give a little more insight.

I'll look into this.

> Anyways, since this change gives 10% boost overall even in the worst case this seems like a good candidate for merging. I think my only concern would be to make sure that we don't have a massive regression (broken or much slower) in some of the older browser versions that we still want to support.

Yeah.  I run on the bleeding edge for Firefox (nightly) and fairly recent for Chromium (just recompiled to 44), so I was hoping some other people could give some feedback about their experience in commonly used applications with other browsers.  I'll run some basic tests in SauceLabs as well.

@kanaka: what do you think about the buffer size issue?

> @DirectXMan12 BTW, it might be interesting to compare with an asm.js enabled zlib implementation: https://github.com/ukyo/zlib-asm That does mean getting an emscripten toolchain working, but since we probably want to switch a lot of the noVNC fast path to asm.js at some point, this might be a good place to start experimenting. I might even have some time to work on it this summer if you don't, although no promises. 

Yeah, I considered this.  The issues are that asm.js is generally less performant than well-written code on Chrome (http://blog.kazuhooku.com/2013/12/benchmarking-asmjs-using-real-world.html) at the moment, unfortunately.

The other issue (not with asm.js code, but with zlib-asm) is that zlib-asm (as well as other zlib libraries) don't have APIs designed for the use case used in RFB -- having a stream and getting partial results out of that stream.  Fortunately for us, pako presents a low-level API similar to the actual zlib API, so we can use that.

> There is a lot of potential areas for noVNC performance improvements: binary types, asm.js, web workers (especially now that firefox supports WebSockets in workers), SIMD.js, etc

One of these days I'm going to get around to the major refactor for ArrayBuffer usage.  One of the big issues is that allocating new ArrayBuffer seems to be more expensive than allocating Arrays, so you want to try not to make lots of new ArrayBuffer objects.  This would probably involve a lot more passing around indicies pointing to locations inside of ArrayBuffers instead of passing around new Arrays, like we do now.

**Comment by DirectXMan12** [comment]
Oh, and FYI, there's a bug fix in there that I should really pull out before merge -- there's a bug-type-thing when noVNC is used with Firefox Nightly that somehow causes the encoding handler object to not have objects defined.  It acts like a race condition (it doesn't seem to appear when run with a debugger, it only appears during times of rapid throughput, etc), but I can't seem to track down what exactly is going on.  The "solution" is essentially to check if the encoding handler is null and then try again.  I hope to have a better solution at some point.

**Comment by DirectXMan12** [comment]
superseded by #488

**Pull request closed without merging**
