### PR TITLE
Added Greek translation

### PR DESCRIPTION
**Pull request by kosmasgiannis**
I added the Greek locale for the messages appearing in the statusbar. 
I hope it is ok.

### CODE REVIEW

**Comment by samhed** [comment]
Thank you!

The strings "invalid state" and "unable to create RFB client" were removed in 91e41150f0782425b41fc1bc75a0af85cb7f52b6 since I believe we shouldn't translate error messages for unexpected failures. Especially these two examples are cases of code errors. The main action here is logging via "Util.Error" but they were also added to the status bar for extra visibility due to their fatal nature.

So, the translation for the last two strings isn't needed.

**Comment by kosmasgiannis** [comment]
I removed the translations of the error messages for unexpected failures. I 'm afraid I messed up the pull request a little bit. I can make a new pull request if necessary.

**Comment by samhed** [comment]
hehe okay, you should be fine if you rebase!

For your example, if your commits are:

* 1 Unwanted commit
* 2 Unwanted commit
* 3 Unwanted commit
* 4 Unwanted commit
* 5 Remove translations related to error messages for unexpected failures
* 6 Added Greek translation
* 7 Unwanted commit

After you run "git rebase -i master" you should get a list of commits for the rebase in your editor. The list is ordered with oldest commit at the top:

    pick 1 unwanted commit
    pick 2 unwanted commit
    pick 3 Added greek translation
    pick 4 unwanted commit
    pick 5 Remove translations related to error...
    pick 6 unwanted commit
    pick 7 unwanted commit

 You should modify the list to instead be:

    pick 3 Added greek translation
    squash 5 Remove translations related to error...

How does that work for you?

**Comment by kosmasgiannis** [comment]
Hi and thanks for the hints. 

I rebased master and on my local branch it looks fine but when I try to push to the remote branch I get the following : 

    To https://github.com/kosmasgiannis/noVNC.git
     ! [rejected]        locale-el -> locale-el (non-fast-forward)
    error: failed to push some refs to 'https://github.com/kosmasgiannis/noVNC.git'
    hint: Updates were rejected because the tip of your current branch is behind
    hint: its remote counterpart. Integrate the remote changes (e.g.
    hint: 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Unfortunately, if I issue `git pull` it gets me back to the previous state. 

Any suggestions?

**Comment by kosmasgiannis** [comment]
I think `git push -f` fixed the mess.

**Pull request merged**
