### PR TITLE
Issue#311: Can't show Chinese VM name correctly

### PR DESCRIPTION
**Pull request by hlwanghl**
Chinese characters have 3 bytes each after decoded by base64, and we need
combine 3 bytes into 1 2-byte unicode for String.fromCharCode(number); to
decode the character correctly.

Signed-off-by: Hongliang Wang <hlwang@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by samhed** [comment]
I think this might be a good feature to have, did you have any remaining concerns @DirectXMan12 ?

**Comment by DirectXMan12** [comment]
Sorry about the delay, it appears I got sidetracked.  The commit needs to be squashed and updated, and also needs tests.

Additionally, I'd like a little more clarification, if possible, as to where the issue lies.

Since I don't speak/use Chinese, I'm unsure as to what's not functioning correctly.  However, using our current logic:

```javascript

var s = String.fromCharCode.apply(null, [0xe6, 0x88, 0x91]);
console.log(decodeURIComponent(escape(s)));
```

in the Firefox JS console, gives me "我" (the correct character).

**Comment by samhed** [comment]
Poke @hlwanghl so we can proceed with this PR!

**Comment by hlwanghl** [comment]
That's cool 😎

发自我的 Windows Phone
________________________________
发件人: Samuel<mailto:notifications@github.com>
发送时间: ‎2015/‎3/‎25 9:08
收件人: kanaka/noVNC<mailto:noVNC@noreply.github.com>
抄送: Hongliang Wang<mailto:hlwanghl@hotmail.com>
主题: Re: [noVNC] Issue#311: Can't show Chinese VM name correctly (#365)

Poke @hlwanghl so we can proceed with this PR!

---

**Comment by samhed** [comment]
> That's cool :sunglasses:

Ehm, @DirectXMan12 asked you to clarify the problem. That's why I poked you.

**Comment by DirectXMan12** [comment]
@hlwanghl : please respond, or I will close this PR.

**Comment by hlwanghl** [comment]
Hi Solly,

Sorry for the delay, but I don't have a chance to take a look and it's difficult to reproduce for me because I've left the Kimchi project from which this PR originated. I'll try to contact Kimchi team to give you an update.

发自我的 Windows Phone
________________________________
发件人: Solly<mailto:notifications@github.com>
发送时间: ‎2015/‎4/‎8 2:04
收件人: kanaka/noVNC<mailto:noVNC@noreply.github.com>
抄送: Hongliang Wang<mailto:hlwanghl@hotmail.com>
主题: Re: [noVNC] Issue#311: Can't show Chinese VM name correctly (#365)

@hlwanghl : please respond, or I will close this PR.

---

**Comment by DirectXMan12** [comment]
Closing due to no response

**Pull request closed without merging**
