### PR TITLE
Clean up page icons ("favicon")

### PR DESCRIPTION
**Pull request by CendioOssman**
Get everything nice and standards compliant. Also sorts out some high resolution versions of the icon. :)

This also removes the iOS startup image as Apple seems to have silently dropped that feature in iOS 9.

### CODE REVIEW

**Comment by samhed** [comment]
How many platforms did you test this on? Would be nice to have this verified to be working on recent versions of:

* Linux: Firefox, Chrome
* Windows: IE, Edge, Firefox, Chrome
* MacOS: Safari, Firefox, Chrome
* Android: Firefox, Chrome
* iOS: Safari, Firefox, Chrome

**Comment by CendioOssman** [comment]
Windows and macOS haven't been tested. I'd wager Firefox and Chrome work the same there though, so it's Safari, IE and Edge that needs testing.

**Comment by CendioOssman** [comment]
I've now tested Safari, IE and Edge. No regressions seen.

**Comment by samhed** [comment]
Good enough for me! Thanks for testing

**Pull request merged**
