### PR TITLE
[WIP] Reduce GC Spikes in Firefox w/o JPEG mode

### PR DESCRIPTION
**Pull request by DirectXMan12**
See #559

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@samhed PTAL when you get a chance

**Comment by samhed** [comment]
On it.

**Comment by samhed** [comment]
I will continue with this on Monday.

**Comment by samhed** [comment]
I have tested this today, I am not seeing any problems. But see #559

**Comment by samhed** [comment]
I find it difficult to see if we want these changes even though the problem ( #559 ) isn't possible to reproduce anymore?

If we want them, we have to at least remove the comments from the code and fix the unit tests.

**Pull request closed without merging**
