### PR TITLE
Localization support added for messages

### PR DESCRIPTION
**Pull request by LoekJanssen**
I created localization in German, Dutch and English for the messages in
the top messagebar and some logs.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Localization support would be great!  However, could you please fix the failing unit tests so that they work with you patch?  Thanks!

**Comment by LoekJanssen** [comment]
Nice to hear its a good addition. I'm setting up a test environment as i'm typing this. I'v got some problems getting the environment to work..

**Comment by samhed** [comment]
Apologies for the slow response, it would be nice if you could squash at least the unit test-commits :)

**Comment by DirectXMan12** [comment]
@samhed @CendioOssman how does this fit with #653?  Can you cherry-pick this into your changes (keeping commit attribution, etc)?

**Comment by samhed** [comment]
Instead of having a key to lookup the values, could we instead use the full English string? Makes the code much easier to read plus that you don't have to look in a different file to see the actual string.

**Comment by CendioOssman** [comment]
> Instead of having a key to lookup the values, could we instead use the full English string? Makes the code much easier to read plus that you don't have to look in a different file to see the actual string.

+1
This is how it is commonly done elsewhere, usually using gettext.

Also, note that there are strings in the HTML as well that would need translation.

**Comment by kanaka** [comment]
+1 for localization. Also, +1 for using the full English strings as the lookup. One additional advantage of that is that if the key is used for the default translations that even the translation is missing for certain text elements (which is pretty much guaranteed when new texts are first added), then the user gets the full text (albeit untranslated) rather than just a internal token.

I would also request that the localization function is aliased to `_` in the modules that use it. This is pretty standard practice and avoids modifying the general appearance of the code with verbose function calls for every piece of UI text.

**Comment by edfink** [comment]
+1 for interest. I'd really like to have these strings translated as well.

A quick look at the change has me wondering about string substitution instead of concatenation in a few places.

**Comment by DirectXMan12** [comment]
> I would also request that the localization function is aliased to _ in the modules that use it. This is pretty standard practice and avoids modifying the general appearance of the code with verbose function calls for every piece of UI text.

That's probably not the best idea, unless we take pains to make sure it's scoped well, otherwise it'll conflict with underscore.js, etc.

**Comment by kanaka** [comment]
@DirectXMan12 yes, sorry, I wasn't clear enough. I was intending to suggest a scoped variable i.e. in RFB object a local variable alias `_` is created for `Util.Localisation.get`.

**Comment by DirectXMan12** [comment]
> I was intending to suggest a scoped variable i.e. in RFB object a local variable alias `_` is created for `Util.Localisation.get`.

ah, ok, that's fine :+1:

**Comment by LoekJanssen** [comment]
I created a fork of the latest version of noVNC and merged the localization changes with that version because of the amount of conflicts and changes. It's an option to close this pull request, I will create a new one soon. (once all translations are finished)

**Comment by samhed** [comment]
@LoekJanssen very nice to hear!! Any chance you could also have a look at using the full english string for lookup?

You don't have to create a new PR, you can just rebase and push --force this one.

**Comment by CendioOssman** [comment]
Have you looked at Jed rather than inventing your own thing? It seems to be the popular alternative to gettext in the Javascript world.

**Comment by LoekJanssen** [comment]
I've used full English strings for lookup.

Thanks for bringing Jed to my attention, I didn't know about it. So I haven't used Jed for noVNC, but I think the current version is straightforward and lightweight already. I will update the code soon so you can have a look.

**Comment by LoekJanssen** [comment]
I accidentally removed the branch connected to this pull request...
I've got a new branch merged with the latest changes ready. Can I create a new pull request?

**Comment by CendioOssman** [comment]
Have you tried creating a new branch with the same name? That might resolve things.

**Comment by LoekJanssen** [comment]
@CendioOssman mine is just called noVNC. The same as before.

**Comment by CendioOssman** [comment]
Oh, you mean you removed the entire repository, not just the branch?

**Comment by LoekJanssen** [comment]
Ah yes, that's what I meant

**Comment by LooksgoodNL** [comment]
I've created a new clean pull request. This one is now old and can be closed. New: #701

**Pull request closed without merging**
