### PR TITLE
Resize Receive Queue to Fit Incoming Messages

### LINKED ISSUE #557: RangeError with Raw encoding at websock.js
I have a custom app that communicates via RFB protocol. It use noVNC to display UI. Using Hextile encoding is ok, switching to Raw periodically produce the following exceptions:

```
recv_message, caught exception: 
    name: RangeError
    message: Source is too large
RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.Websock._decode_message (http://localhost:8080/widget/include/websock.js:346:22)
    at Object.Websock._recv_message (http://localhost:8080/widget/include/websock.js:352:22)
```
I'm not seeing errors in Raw encoding at my app side, but they can be there) However I think anyway noVNC should deal with this gracefully.
Could someone give me a clue why it happens?

### PR DESCRIPTION
**Pull request by DirectXMan12**
This PR causes the receive queue to be resized in order to fit incoming messages.  There is a hard cap of a size of 40 MiB, so that we can't consume too much memory by accident.

Fixes #557

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@kanaka @samhed look good to you?

**Comment by kanaka** [comment]
@DirectXMan12 looks good. Should we add a test for this function?

**Comment by DirectXMan12** [comment]
> Should we add a test for this function.

Yep, good catch.  Will do.

**Comment by DirectXMan12** [comment]
@kanaka test added.  I'll merge shortly unless anyone has any objections.

**Comment by kanaka** [comment]
@DirectXMan12 no objections here.

**Comment by samhed** [comment]
LGTM!

**Pull request merged**
