### PR TITLE
Fix view only

### PR DESCRIPTION
**Pull request by samhed**
This PR fixes a number of issues with view-only:

* Keyboard and mouse were grabbed even in view-only (#644)
* A view-only session could change the desktop size
* The UI modified the keyboard and the mouse in view-only

### CODE REVIEW

**Comment by kanaka** [comment]
I haven't tested, but I've reviewed the changes and they LGTM.

**Comment by samhed** [comment]
I have tested that it works with vnc.html and vnc_auto.html. I would love if @bravegnu could check if it solves his usecase as well.

**Comment by DirectXMan12** [comment]
Needs rebase to fit with new file structure.

**Comment by samhed** [comment]
> Does it make sense to also hide the keyboard-related and mouse-related buttons in view-only mode? That could be a follow-up PR

Absolutely! In fact, I can add that after I rebase

**Comment by samhed** [comment]
Rebased and added hiding of input related UI elements.

**Pull request merged**
