### PR TITLE
Don't send Unicode as keysym

### PR DESCRIPTION
**Pull request by ossman**
We had a bug where we would send a Unicode codepoint as a keysym to the server. This of course ended up with a completely wrong symbol.

Also made sure we can transfer the entire Unicode range.

### CODE REVIEW

**Comment by samhed** [comment]
The changes to test.helper.js seem to cause at least the Travis-tests to fail, do they work for you?

**Comment by samhed** [comment]
Do you have a specific example of something that was fixed by this?

**Comment by ossman** [comment]
The tests were buggy and I fixed them as part of this. A result of this is that it requires ECMAscript 6. It works fine here, but your Travis instance doesn't seem to handle it. Perhaps the test needs to be changed to something simpler. 

As for what was fixed, a lot of characters on virtual keyboards were wrong. One easy example are smileys.

**Comment by samhed** [comment]
@DirectXMan12 can we update Node JS on our travis?

**Comment by DirectXMan12** [comment]
> can we update Node JS on our travis?

Yeah, that shouldn't be a problem.

**Comment by samhed** [comment]
I don't seem to be able to access settings for travis

**Comment by DirectXMan12** [comment]
@samhed you should be able to change the version of node.js via .travis.yml.  The actual issue here probably PhantomJS, though.  I'll have to figure out what version of PhantomJS the karma launcher is pulling.

**Pull request merged**
