### PR TITLE
Support ExtendedDesktopSize and SetDesktopSize

### PR DESCRIPTION
**Pull request by samhed**
Cleaned up version of #271 

This feature is divided into 4 commits:
1: display.js
2: rfb.js
3: ui.js, vnc.html & vnc_auto.html
4: tests

### CODE REVIEW

**Comment by DirectXMan12** [comment]
LGTM :+1:  Just needs tests.  It will be great to have this.

P.S. For future reference, you don't have to open a new PR -- you can just edit the existing branch that the PR is based off of (`git rebase -i`, or something like that locally, and then `git push --force`)

**Comment by samhed** [comment]
There we go, I think these tests should be sufficient, the changes in display.js should be covered by existing tests. I think ui changes are difficult to write unit tests for since they are closely dependent on HTML elements?

>P.S. For future reference, you don't have to open a new PR -- you can just edit the existing branch that the PR is based off of (git rebase -i, or something like that locally, and then git push --force)

Will do!

**Comment by DirectXMan12** [comment]
The unit tests look good.  I caught one last thing right before I went to merge, however.  If you can fix that, I'll merge the patch.

**Comment by samhed** [comment]
Good catch, thank you! Should all be good now.

**Pull request merged**
